package org.contact.dao;

import java.util.List;

import org.contact.model.PARAMETROS;

public interface JdbcDaoParametrosInterface {
	
	public  List<PARAMETROS> OBTENER_PARAMETROS_PARA_EL_USUARIO_LOGGEADO(String PARAMETROS);
	public  List<PARAMETROS>OBTENER_PARAMETRO_DESEADO_PARA_LISTA(String PARAMETRO) ;
	public  PARAMETROS OBTENER_PARAMETRO_DESEADO_PARA_OBJETO_POR_ID_PARAMETRO(int PARAMETRO);
	public  PARAMETROS OBTENER_PARAMETRO_DESEADO_PARA_OBJETO_POR_CLAVE(String PARAMETRO);
	public  void UPDATE_PARAMETRO(PARAMETROS PARAMETRO_A_ACTUALIZAR) ;
	public  void ELIMINAR_PARAMETRO(int ID) ;
	public  void AGREGAR_PARAMETRO(PARAMETROS NUEVO_PARAMETRO) ;
	public List<PARAMETROS> SELECT_LIKE(String VALOR_BUSCADO,String PARAMETROS_DISPONIBLES);
	
}
